---
name: open-interfaces

channels:
    - conda-forge

dependencies:
    - python=3.11
    - cmake=3.18
    - pip
    - c-compiler=1.5.1
    - cxx-compiler=1.5.1
    - fortran-compiler
    - numpy
    - openblas
    - pytest
    - python-dotenv
    - flake8
    - black
    - mypy
    - isort
    - pip:
          - sphinx
          - myst_parser
