name: open-interfaces

channels:
    - conda-forge

dependencies:
    - python=3.10
    - cmake=3.18
    - pip
    - c-compiler=1.5.1
    - cxx-compiler=1.3.0
    - fortran-compiler
    - openblas
    - pytest
    - python-dotenv
    - flake8
    - black
    - mypy
    - isort
