name = "OpenInterfacesImpl"
uuid = "daff4927-7858-4806-96da-915047fb441c"
authors = ["Dmitry Kabanov <dmitry.kabanov@uni-muenster.de>", "Stephan Rave <stephan.rave@uni-muenster.de", "Mario Ohlberger <mario.ohlberger@uni-muenster.de"]
version = "0.6.3"

[deps]
MsgPack = "99f44e22-a591-53d1-9472-aa23ef4bd671"
OpenInterfaces = "07cfd324-e924-40a7-85fa-5e46307e7ad7"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
SciMLBase = "0bca4576-84f4-4d90-8ffe-ffa030f20462"

[compat]
MsgPack = "1.2.1"
OrdinaryDiffEq = "6.102.1"
SciMLBase = "2.120.0"
