name = "OpenInterfaces"
uuid = "07cfd324-e924-40a7-85fa-5e46307e7ad7"
authors = ["Dmitry Kabanov <dmitry.kabanov@uni-muenster.de>", "Stephan Rave <stephan.rave@uni-muenster.de", "Mario Ohlberger <mario.ohlberger@uni-muenster.de"]
version = "0.6.0"

[deps]
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
MsgPack = "99f44e22-a591-53d1-9472-aa23ef4bd671"

[compat]
Libdl = "1.11.0"
MsgPack = "1.2.1"
