name = "OpenInterfaces"
uuid = "07cfd324-e924-40a7-85fa-5e46307e7ad7"
authors = ["Dmitry Kabanov <dmitry.kabanov@uni-muenster.de>", "Stephan Rave <stephan.rave@uni-muenster.de", "Mario Ohlberger <mario.ohlberger@uni-muenster.de"]
version = "0.5.5"

[deps]
Debugger = "31a5f54b-26ea-5ae9-a837-f05ce5417438"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"

[compat]
Debugger = "0.7.13"
Libdl = "1.11.0"
