---
name: Build Images

on:
    workflow_call:
        outputs:
            matrix-combinations:
                description: json data describing the build matrix
                value: ${{ jobs.matrix-setup.outputs.matrix-combinations }}
            image_tag:
                description: a string to identify the generated docker image, needs to postfixxed with ${CC}
                value: ${{ jobs.metadata.outputs.tags }}

concurrency:
    # resolves to the caller workflow: ${{ github.workflow }}
    group: build_images_${{ github.event.pull_request.head.label || github.head_ref || github.ref }}
    cancel-in-progress: false

jobs:
    matrix-setup:
        runs-on: ubuntu-22.04
        steps:
            - name: Setup matrix combinations
              id: setup-matrix-combinations
              run: |
                  echo 'matrix-combinations<<EOF' >> $GITHUB_OUTPUT
                  echo '{"include":[{"CC": "clang", "CXX": "clang++"},
                      {"CC": "gcc", "CXX": "g++"},]}' >> $GITHUB_OUTPUT
                  echo 'EOF' >> $GITHUB_OUTPUT
        outputs:
            matrix-combinations: ${{ steps.setup-matrix-combinations.outputs.matrix-combinations }}

    metadata:
        runs-on: ubuntu-22.04
        needs: matrix-setup
        steps:
            - uses: actions/checkout@v3
            - name: Docker meta
              id: meta
              uses: docker/metadata-action@v4
              with:
                  images: ghcr.io/${{github.repository}}/ci_test
                  flavor: |
                      latest=false
                  tags: |
                      type=sha,suffix=-g{{branch}}
        outputs:
            tags: ${{steps.meta.outputs.tags}}
    build:
        runs-on: ubuntu-22.04
        needs: [metadata, matrix-setup]
        strategy:
            matrix: ${{ fromJson(needs.matrix-setup.outputs.matrix-combinations) }}
        permissions:
            packages: write
        steps:
            - uses: actions/checkout@v3
            - name: Set up Docker Buildx
              id: buildx
              uses: docker/setup-buildx-action@v3
            - name: Login to Github Packages
              uses: docker/login-action@v2
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}
            - name: Build
              uses: docker/build-push-action@v4
              with:
                  context: .
                  push: true
                  cache-from: type=registry,ref=${{ needs.metadata.outputs.tags }}_${{matrix.CC}}_buildcache
                  cache-to: type=registry,ref=${{ needs.metadata.outputs.tags }}_${{matrix.CC}}_buildcache,mode=max
                  tags: ${{ needs.metadata.outputs.tags }}_${{matrix.CC}}
                  build-args: |
                      M2_CC=${{matrix.CC}}
                      M2_CXX=${{matrix.CXX}}
