---
name: build and test

on: [push, pull_request]

jobs:
    build-test:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                include:
                    - CXX: clang++
                      CC: clang
                    - CXX: g++
                      CC: gcc

        steps:
            - uses: actions/checkout@v3
            - name: Set up Docker Buildx
              id: buildx
              uses: docker/setup-buildx-action@v2
            - name: Login to Github Packages
              uses: docker/login-action@v2
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}
            - name: Docker meta
              id: meta
              uses: docker/metadata-action@v4
              with:
                  images: ghcr.io/mardi4nfdi/open-interfaces/ci_test
                  flavor: |
                      latest=false
                      suffix=${{matrix.CC}}
                  tags: |
                      type=ref,event=branch
                      type=ref,event=pr
            - name: Build
              uses: docker/build-push-action@v3
              with:
                  context: .
                  push: false
                  load: true
                  tags: ${{ steps.meta.outputs.tags }}
                  labels: ${{ steps.meta.outputs.labels }}
                  build-args: |
                      M2_CC=${{matrix.CC}}
                      M2_CXX=${{matrix.CXX}}
            - name: Test
              run: |
                  docker run --rm ${{ steps.meta.outputs.tags }}
            - name: Build
              uses: docker/build-push-action@v3
              with:
                  context: .
                  push: true
                  tags: ${{ steps.meta.outputs.tags }}
                  labels: ${{ steps.meta.outputs.labels }}
                  build-args: |
                      M2_CC=${{matrix.CC}}
                      M2_CXX=${{matrix.CXX}}
