---
name: Julia Test

on:
    push:
        branches:
            - main
    pull_request:


jobs:
    test:
        name: Julia Native Tests
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix:
                version:
                    - '1.8'
                    - nightly
                os:
                    - ubuntu-22.04
# needs cross-platform library loading
#                    - windows-2022
                arch:
                    - x64
                flags:
                    # TODO not necessary for linux
                    - -DOIF_USE_R=0

        steps:
            - uses: actions/checkout@v4
            - uses: julia-actions/setup-julia@v1
              with:
                  version: ${{ matrix.version }}
            - run: julia -e 'using InteractiveUtils; versioninfo(verbose=true)'
            - uses: julia-actions/cache@v1
            - uses: actions/setup-python@v4
              with:
                  # 3.9 current max for which bin wheel on windows exist
                  # https://pypi.org/project/lxml/#files
                  python-version: '3.9'
# currently disabled via matrix.flags
#            - name: Install R
#              if: matrix.os == 'windows-2022'
#              uses: r-lib/actions/setup-r@v2
#              with:
#                  r-version: release
            - name: Install Flexiblas
              run: |
                  cd /tmp
                  wget https://rene.fritze.me/flexiblas//releases/3.2.1/flexiblas_ubuntu-kinetic.zip -O debs.zip
                  unzip -j debs.zip
                  sudo apt install -y --no-install-recommends ./libflexiblas_3.2.1_amd64.deb ./libflexiblas-dev_3.2.1_amd64.deb ./libflexiblas-openblas-pthread_3.2.1_amd64.deb ./libflexiblas_3.2.1_amd64.deb ./libflexiblas-bin_3.2.1_amd64.deb
            - name: Configure
              run: cmake -B ${{github.workspace}}/cmake-build ${{matrix.flags}}
            - name: Build
              run: cmake --build ${{github.workspace}}/cmake-build
            - name: Install
              run: sudo cmake --build ${{github.workspace}}/cmake-build --target install
            - name: Setup Environment 1/2
              run: grep -v "#" /usr/local/share/oif_pytest.env > oif_pytest.env
            - name: Setup Environment 2/2
              uses: krisalay/export-env@v1.0.1
              with:
                  filename: oif_pytest.env
            - uses: julia-actions/julia-buildpkg@v1
              name: Build Julia
              with:
                  project: lang_julia/package/
            - name: Run tests
              uses: julia-actions/julia-runtest@v1
              with:
                  coverage: true
                  project: lang_julia/package/
                  annotate: true
#    - uses: julia-actions/julia-processcoverage@v1
#      with:
#        directories: src,examples
#    - uses: codecov/codecov-action@v1
#      with:
#        file: ./lcov.info
#        flags: unittests
#        name: codecov-umbrella
#        fail_ci_if_error: false
#    - uses: actions/upload-artifact@v2
#      with:
#        path: ./lcov-info
