---
name: Julia Test

on:
    push:
        branches:
            - main
    pull_request:


jobs:
    test:
        name: Julia Native Tests
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix:
                version:
                    - '1.8'
                    - nightly
                os:
                    - ubuntu-22.04
# needs cross-platform library loading
#                    - windows-2022
                arch:
                    - x64
                flags:
                    # TODO not necessary for linux
                    - -DOIF_USE_R=0

        steps:
            - uses: actions/checkout@v2
            - uses: julia-actions/setup-julia@v1
              with:
                  version: ${{ matrix.version }}
            - run: julia -e 'using InteractiveUtils; versioninfo(verbose=true)'
            - uses: julia-actions/cache@v1
            - uses: actions/setup-python@v4
              with:
                  # 3.9 current max for which bin wheel on windows exist
                  # https://pypi.org/project/lxml/#files
                  python-version: '3.9'
# currently disabled via matrix.flags
#            - name: Install R
#              if: matrix.os == 'windows-2022'
#              uses: r-lib/actions/setup-r@v2
#              with:
#                  r-version: release
            - name: Configure
              run: cmake -B ${{github.workspace}}/cmake-build -DOIF_USE_C=0 -DOIF_USE_CPP=0 ${{matrix.flags}}
            - name: Build
              run: cmake --build ${{github.workspace}}/cmake-build
            - name: Install
              run: cmake --build ${{github.workspace}}/cmake-build
            - uses: julia-actions/julia-buildpkg@v1
              name: Build Julia
              with:
                  project: lang_julia/package/
            - name: Run tests
              uses: julia-actions/julia-runtest@v1
              with:
                  coverage: true
                  project: lang_julia/package/
                  annotate: true
#    - uses: julia-actions/julia-processcoverage@v1
#      with:
#        directories: src,examples
#    - uses: codecov/codecov-action@v1
#      with:
#        file: ./lcov.info
#        flags: unittests
#        name: codecov-umbrella
#        fail_ci_if_error: false
#    - uses: actions/upload-artifact@v2
#      with:
#        path: ./lcov-info
