---
name: QA conda

on:
    - push
    - pull_request

jobs:
    qa-linux-conda:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version: ['3.9', '3.10']
        defaults:
            run:
                shell: bash -l {0}

        steps:
            - name: Check out repository code
              uses: actions/checkout@v4
            - name: Setup conda environment
              uses: conda-incubator/setup-miniconda@v3
              with:
                  auto-activate-base: false
                  activate-environment: test
                  environment-file: environment-linux.yaml
                  python-version: ${{ matrix.python-version }}
            - name: Show info
              run: |
                  conda activate test
                  conda info
                  type gcc
                  type g++
                  type python
                  type pip
            - name: Build
              run: make
            - name: Run tests
              run: make test
