---
name: QA conda

on:
    push:
        branches:
            - 'main'
    pull_request:
        types: ['opened', 'synchronize', 'reopened']

jobs:
    qa-ubuntu-conda:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version: ['3.10', '3.11', '3.12']
        defaults:
            run:
                shell: bash -l {0}

        steps:
            - name: Check out repository code
              uses: actions/checkout@v4
            - name: Cache conda packages
              uses: actions/cache@v3
              env:
                # Increase this value to reset cache if environment.yaml has not changed
                  CACHE_NUMBER: 1
              with:
                  path: ~/conda_pkgs_dir
                  key: ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{ hashFiles('environment-linux.yaml') }}
            - name: Setup conda environment
              uses: conda-incubator/setup-miniconda@v3
              with:
                  activate-environment: test
                  environment-file: environment-linux.yaml
                  miniforge-version: latest
                  mamba-version: '*'
                  python-version: ${{ matrix.python-version }}
            - name: Show info
              run: |
                  conda info
                  type gcc
                  type g++
                  type python
                  type pip
                  git status
            - name: Build
              run: |
                  make
            - name: Run tests
              run: |
                  make test
