---
name: Containerized Test

on:
    push:
        branches:
            - main
    pull_request:

concurrency:
    group: ${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}
    cancel-in-progress: true

jobs:
    build_images:
        uses: ./.github/workflows/build_images.yml
    test:
        runs-on: ubuntu-22.04
        needs: [build_images]
        name: Run Containerized Tests
        strategy:
            matrix: ${{ fromJson(needs.build_images.outputs.matrix-combinations) }}
        steps:
            - name: Login to Github Packages
              uses: docker/login-action@v2
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}
            - name: Test
              run: |
                  docker run --rm ${{ needs.build_images.outputs.image_tag }}_${{matrix.CC}}
